accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('sign-up/',views.sign_up,name='sign_up'),
    path('sign-out/',views.sign_out,name='sign_out'),
    path('sign-in/',views.sign_in,name='sign_in'),
    path('view-profile/',views.view_profile,name='view_profile'),
    path('edit-profile/',views.edit_profile,name='edit_profile'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('',views.subject_courses_list,name='subject_courses_list'),
    path('course/<slug:slug>/',views.course_detail,name='course_detail'),
    path('add-course/',views.add_course,name='add_course'),
    path('edit-course/<slug:slug>/',views.edit_course,name='edit_course'),

    path('course/<slug:slug>/add-module/',views.add_module , name='add_module') , 
    path('enroll-course/<slug:slug>/',views.enroll_course,name='enroll_course'),

    
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('courses.urls',namespace='courses')),
    path('accounts/',include('accounts.urls',namespace='accounts'))
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class InstructorProfile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE , related_name='profile')
    bio = models.TextField(blank=True,null=True)
    photo = models.ImageField(upload_to='instructors/photos',null=True,blank=True)
    contact_email = models.EmailField(blank=True,null=True)
    header = models.CharField(max_length=255,blank=True,null=True)

    def __str__(self) -> str :
        return str(f'Profile of {self.user.username}')
    
class SocialMediaAccounts(models.Model):
    user = models.OneToOneField(InstructorProfile,on_delete=models.CASCADE,related_name='socialmedia')
    linkedin = models.URLField(blank=True,null=True)
    github = models.URLField(blank=True,null=True)
    facebook = models.URLField(blank=True,null=True)
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import InstructorProfile


class SignUpForm(UserCreationForm):
    ROLE_CHOICES = (
        ('students','Students'),
        ('instructor','Instructor')
    )
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'E-mail'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))
    role = forms.ChoiceField(choices=ROLE_CHOICES,required=True)
    

    class Meta :
        model = User
        fields = ['username','email','password1','password2']


        
class InstructorProfileForm(forms.ModelForm):
    class Meta :
        model = InstructorProfile
        fields = ['bio','photo','contact_email','header']

accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import SignUpForm , InstructorProfileForm
from django.contrib.auth import login ,logout , authenticate
from .models import InstructorProfile 
from django.contrib.auth.decorators import login_required
from courses.models import Course


# Create your views here.

def sign_up(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            InstructorProfile.objects.create(user=user)
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')


            user = authenticate(request ,username=username , password=password)
            if user is not None :
                login(request , user)
                return redirect('accounts:view_profile')
    context = {
        'form':form ,
    }
    return render(request,'accounts/sign_up.html',context)


def sign_out(request):
    logout(request)
    return redirect('accounts:sign_in')


def sign_in(request):
    ERROR = None
    if request.user.is_authenticated :
        return redirect('courses:subject_courses_list')
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username=username,password=password)
        if user is not None :
            login(request,user)
            return redirect('accounts:view_profile')
        else :
            ERROR = 'Invalid credeticats!, Password or Username is invalid!'

    context = {
        'error':ERROR
    }

    return render(request,'accounts/sign_in.html',context)

@login_required(login_url='accounts:view_profile')
def view_profile(request):
    profile =get_object_or_404(InstructorProfile,user=request.user)
    courses = Course.objects.filter(owner = request.user)
    context = {
        'profile':profile ,
        'courses' : courses
    }

    return render(request,'accounts/view_profile.html',context)



@login_required(login_url='accounts:edit_profile')
def edit_profile(request):
    profile = get_object_or_404(InstructorProfile,user = request.user)
    form = InstructorProfileForm(instance=profile)
    if request.method == 'POST':

        form = InstructorProfileForm(request.POST,request.FILES , instance=profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:view_profile')
    
    context = {
        'form':form
    }
    return render(request,'accounts/edit_profile.html',context)

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load tailwind_filters %}




{% block title %}
    Edit-Profile
{% endblock title %}
    



{% block content %}
<div class="flex justify-center items-center min-h-screen bg-gray-100">
    <div class="w-full max-w-md bg-white p-8 rounded-lg shadow-lg">
        <h2 class="text-2xl font-bold text-center text-gray-700 mb-6">Edit-Profile</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
          {{form|crispy}}

          <div class="mb-6">
            <button type="submit" class="w-full px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 focus:outline-none">Save</button>
        </div>
             
        </form>
    </div>
</div>
{% endblock content %}
    

templates/accounts/sign_in.html
{% extends 'base.html' %}
{% load tailwind_filters %}



{% block title %}
    Sign-In
{% endblock title %}
    



{% block content %}
    

            
<div class="flex justify-center items-center min-h-screen bg-gray-100">
    <div class="w-full max-w-md bg-white p-8 rounded-lg shadow-lg">
        <h2 class="text-2xl font-bold text-center text-gray-700 mb-6">Sign In for Learning Platform</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="mb-6">
                <label >Username</label>
                <input type="text"  placeholder="'Enter Username" name="username" class="w-full px-4 py-2  text-white rounded-md " >
            </div>

            <label >Password</label>
            <div class="mb-6">
                <input type="password" placeholder="Enter Password" name="password" class="w-full px-4 py-2  text-white rounded-md " >
            </div>

          <div class="mb-6">
            <button type="submit" class="w-full px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 focus:outline-none">Sign IN</button>
        </div>
                    <div class="text-center">
                <p class="text-sm text-gray-600">Don't have an account? <a href="{% url 'accounts:sign_up' %}" class="text-indigo-600 hover:underline">Sign UP</a></p>
            </div>
        </form>
    </div>
</div>


{% endblock content %}
    

templates/accounts/sign_up.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block title %}
    Sign-Up
{% endblock title %}
    



{% block content %}
    

            
<div class="flex justify-center items-center min-h-screen bg-gray-100">
    <div class="w-full max-w-md bg-white p-8 rounded-lg shadow-lg">
        <h2 class="text-2xl font-bold text-center text-gray-700 mb-6">Sign Up for Learning Platform</h2>
        <form method="POST">
            {% csrf_token %}
                {{ form|crispy }}

          <div class="mb-6">
            <button type="submit" class="w-full px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 focus:outline-none">Sign Up</button>
        </div>
                    <div class="text-center">
                <p class="text-sm text-gray-600">Already have an account? <a href="{% url 'accounts:sign_in' %}" class="text-indigo-600 hover:underline">Sign In</a></p>
            </div>
        </form>
    </div>
</div>


{% endblock content %}
    

templates/accounts/view_profile.html
{% extends 'base.html' %}




{% block title %}
    Profile
{% endblock title %}




{% block content %}
    
    <div class="max-w-7xl mx-auto p-6">
        
        <!-- Profile Card -->
        <div class="bg-white rounded-lg shadow-lg p-6">
            <div class="mt-4">
                <a href="{% url 'accounts:edit_profile' %}"
                    class="inline-block bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition">Edit-Profile
                    </a>
            </div>
            <div class="flex items-center flex-col md:flex-row md:items-start">
                <!-- Profile Picture -->
                <div class="w-40 h-40 rounded-full overflow-hidden border-4 border-blue-500 mb-4 md:mb-0 md:mr-6">
                    
                    {% if profile.photo %}
                    <img src="{{profile.photo.url}}" alt="Instructor Photo" class="w-full h-full object-cover">
                {% else %}
                <img src="#" alt="Instructor Photo" class="w-full h-full object-cover">

                    {% endif %}
                        
                </div>
                <!-- Profile Details -->
                <div class="text-center md:text-left">
                    <h1 class="text-2xl font-bold text-gray-800">{{profile.user.username}}</h1>
                    <p class="text-blue-500 font-medium text-lg mt-2">{{profile.header}}</p>
                    <p class="text-gray-600 mt-4">
                      {{profile.bio}}
                    </p>
                    <div class="mt-4">
                    {% if perms.courses.can_add_course %}  
                        
                        <a href="{% url 'courses:add_course' %}"
                        class="inline-block bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition">
                        Add Course
                        </a>
                    {% else %}
                        
                    {% endif %}
                            
                      
                    </div>
                </div>
            </div>
        </div>
    {% if perms.courses.can_add_course %}
        <!-- Courses Section -->
        <div class="mt-8">
            <h2 class="text-xl font-bold text-gray-800 mb-4">Courses by {{ profile.user.username }}</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                
                {% for course in courses %}
                    
                    
                <!-- Course Card -->
                <div class="bg-white rounded-lg shadow-lg p-4">
                    <img src="https://via.placeholder.com/300x200" alt="Course Thumbnail" class="rounded-lg mb-4">
                    <h3 class="text-lg font-semibold text-gray-800">{{course.title}}</h3>
                    <p class="text-gray-600 mt-2">{{ course.overview }}</p>
                    <a href="{% url 'courses:course_detail' slug=course.slug %}" class="block mt-4 text-blue-500 font-medium hover:underline">View Course →</a>
                    <a href="{% url 'courses:edit_course' slug=course.slug %}" class="block mt-4 text-blue-500 font-medium hover:underline">Edit Course →</a>

                </div>
                {% endfor %}

    {% else %}
    {% endif %}
               
                <!-- Repeat Course Cards as needed -->
            </div>
        </div>






{% endblock content %}
    
    